disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  - class_delegate_protocol
  - legacy_constructor
  - large_tuple
opt_in_rules: # some rules are only opt-in
  - empty_count
  #- missing_docs
  - cyclomatic_complexity
  # Find all the available rules by running:
  # swiftlint rules
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - R.generated.swift
  - Carthage
  - Pods
  - Pods/Realm
  - Pods/InputMask
  - Pods/
  - Pods/*
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - R.generated.swift
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 510
# they can set both implicitly with an array
type_body_length:
  - 1000 # warning
  - 1500 # error
# or they can set both explicitly
file_length:
  warning: 1000
  error: 1500
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 60
    error: 80
  excluded: iPhone # excluded via string
function_parameter_count:
  warning: 15
  error: 30
function_body_length:
  warning: 300
  error: 500
cyclomatic_complexity:
  warning: 50
  error: 70
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - to
    - id
    - ok
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
